Add validation error if token is empty

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -20,6 +20,13 @@ runs:
     - run: poetry build
       shell: bash
       working-directory: ${{ inputs.working-directory }}
+    - name: validate input
+      shell: bash
+      run: |
+        if [ -z "${{ inputs.pypi-token }}" ]; then
+          echo "pypi-token is required"
+          exit 1
+        fi;
     - run: poetry config pypi-token.pypi "${{ inputs.pypi-token }}"
       shell: bash
       working-directory: ${{ inputs.working-directory }}
